package:
  name: lcdblib
  version: {{ LCDBLIB_VERSION }}
source:
  git_url: https://github.com/lcdb/lcdblib.git
  git_rev: master

build:
  number: {{ LCDBLIB_BUILD }}

requirements:
  build:
    - biopython ==1.68
    - ipython ==5.1.0
    - jsonschema ==2.5.1
    - matplotlib ==1.5.3
    - numpy ==1.11.3
    - pandas ==0.19.2
    - pybedtools ==0.7.8
    - pysam ==0.9.1.4
    - pytest ==3.0.5
    - pytest-runner ==2.11
    - pyyaml ==3.12
    - seaborn ==0.7.1
    - snakemake ==3.10.1
  run:
    - biopython ==1.68
    - ipython ==5.1.0
    - jsonschema ==2.5.1
    - matplotlib ==1.5.3
    - numpy ==1.11.3
    - pandas ==0.19.2
    - pybedtools ==0.7.8
    - pysam ==0.9.1.4
    - pytest ==3.0.5
    - pytest-runner ==2.11
    - pyyaml ==3.12
    - seaborn ==0.7.1
    - snakemake ==3.10.1

test:
  imports:
    - lcdblib
    - lcdblib.snakemake.helpers

about:
  home: https://github.com/lcdb/lcdblib
  license: MIT
